---
title: "git_00"
author: "Rafaela Alcivar"
date: "Spring 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->


A boat beneath a sunny sky,  
Lingering onward dreamily  
In an evening of July —  
Children three that nestle near,  
Eager eye and willing ear,  


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->


He is that fallen lance that lies as hurled,  
That lies unlifted now, come dew, come rust,  
But still lies pointed as it plowed the dust.  
If we who sight along it round the world,  
See nothing worthy to have been its mark,  


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->


The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright --  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done --  
'It's very rude of him.' she said,  
'To come and spoil the fun!'  


## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->


When a friend calls to me from the road  
And slows his horse to a meaning walk,  
I don't stand still and look around  
On all the hills I haven't hoed,  
And shout from where I am, What is it?  
No, not as there is a time to talk.  
I thrust my hoe in the mellow ground,  
Blade-end up and five feet tall,  
And plod: I go up to the stone wall  
For a friendly visit.  
